version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./src:/app/src
    command: ["python", "-m", "src.main"]
volumes:
  db-data:
